import type { ScrapingJob, ScraperSource } from "@/lib/types";

export const ACTIVE_SCRAPERS: ScraperSource[] = [
  { id: "facebook", name: "Facebook Marketplace", status: "running", lastRun: "2 min ago", vehiclesFound: 1842, successRate: 98.2 },
  { id: "craigslist", name: "Craigslist", status: "idle", lastRun: "18 min ago", vehiclesFound: 924, successRate: 96.4 },
  { id: "autotrader", name: "AutoTrader", status: "running", lastRun: "1 min ago", vehiclesFound: 3210, successRate: 99.1 },
  { id: "carscom", name: "Cars.com", status: "idle", lastRun: "32 min ago", vehiclesFound: 1568, successRate: 97.8 },
  { id: "cargurus", name: "CarGurus", status: "paused", lastRun: "1 hr ago", vehiclesFound: 1104, successRate: 95.2 },
  { id: "dealer", name: "Dealer Websites", status: "idle", lastRun: "45 min ago", vehiclesFound: 640, successRate: 94.6 },
];

export const SCRAPING_JOBS: ScrapingJob[] = [
  {
    id: "job-1",
    name: "Dallas Trucks",
    marketplace: "Facebook Marketplace",
    searchCriteria: "Ford F-150, Ram 1500 · 2018–2024",
    location: "Dallas, TX · 50 mi",
    frequency: "Every 30 min",
    status: "running",
    vehiclesFound: 428,
    lastRun: "2 min ago",
    startedAt: "Today, 8:14 AM",
    duration: "12m 40s",
  },
  {
    id: "job-2",
    name: "Austin SUVs",
    marketplace: "AutoTrader",
    searchCriteria: "Toyota RAV4, Honda CR-V · Under $30k",
    location: "Austin, TX · 75 mi",
    frequency: "Every 1 hr",
    status: "completed",
    vehiclesFound: 312,
    lastRun: "48 min ago",
    startedAt: "Today, 7:00 AM",
    duration: "8m 12s",
  },
  {
    id: "job-3",
    name: "Houston Craigslist",
    marketplace: "Craigslist",
    searchCriteria: "All makes · Private sellers",
    location: "Houston, TX · 40 mi",
    frequency: "Every 2 hr",
    status: "scheduled",
    vehiclesFound: 186,
    lastRun: "3 hr ago",
    startedAt: "Yesterday, 4:22 PM",
    duration: "15m 08s",
  },
  {
    id: "job-4",
    name: "Phoenix EV Scan",
    marketplace: "Cars.com",
    searchCriteria: "Tesla, EV · 2020+",
    location: "Phoenix, AZ · 60 mi",
    frequency: "Every 4 hr",
    status: "paused",
    vehiclesFound: 94,
    lastRun: "5 hr ago",
    startedAt: "Yesterday, 11:00 AM",
    duration: "6m 44s",
  },
  {
    id: "job-5",
    name: "Atlanta Dealer Feed",
    marketplace: "Dealer Websites",
    searchCriteria: "Certified pre-owned · All makes",
    location: "Atlanta, GA · 100 mi",
    frequency: "Daily",
    status: "completed",
    vehiclesFound: 520,
    lastRun: "6 hr ago",
    startedAt: "Today, 2:00 AM",
    duration: "22m 30s",
  },
  {
    id: "job-6",
    name: "Texas Tacomas",
    marketplace: "CarGurus",
    searchCriteria: "Toyota Tacoma · TRD",
    location: "Texas statewide",
    frequency: "Every 6 hr",
    status: "failed",
    vehiclesFound: 0,
    lastRun: "8 hr ago",
    startedAt: "Yesterday, 10:15 PM",
    duration: "—",
  },
];

export const RECENT_JOBS = SCRAPING_JOBS.slice(0, 5);

export const LIVE_ACTIVITY_MESSAGES = [
  "Found 2022 Toyota Tacoma in Dallas, TX — $28,900",
  "Detected price drop on 2021 Ford F-150 — now $31,200",
  "New listing: 2020 Honda CR-V in Austin — $24,800",
  "Scanned page 142 of Facebook Marketplace results",
  "Found 2019 Chevy Silverado in Houston — $26,400",
  "Price change: 2023 Tesla Model Y dropped $1,200",
  "New private seller listing in Fort Worth — 2021 Ram 1500",
  "Matched criteria: 2022 Jeep Wrangler in Denver",
];
